Rails.application.routes.draw do
  # generated by under_construction gem

  # namespace :admin do
  #   resources :products do
  #     collection do
  #       post :import
  #     end
  #   end
  #   resources :users, only: [:new, :create]
  #   resources :sessions, only: [:new, :create, :destroy]
  #   root 'home#index'
  # end

  root 'welcome#locations'
  # get '/contact', to: 'welcome#contact'
  get '/locations', to: 'welcome#locations'
  # resources :products, only: [:index, :show]
end
